# Generated by Django 3.1.4 on 2020-12-29 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('playlist_name', models.TextField(max_length=100)),
                ('playlist_url', models.CharField(max_length=1000)),
                ('playlist_num_tracks', models.IntegerField(null=True)),
                ('playlist_featured', models.BooleanField(default=False)),
                ('playlist_owner', models.CharField(max_length=500)),
                ('date_created', models.CharField(default='No date', max_length=500)),
                ('playlist_img_src', models.CharField(default='no_img', max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('song_name', models.TextField()),
                ('artist_name', models.CharField(max_length=120)),
                ('song_is_explicit', models.BooleanField()),
                ('song_duration_ms', models.IntegerField()),
                ('recommended_user', models.CharField(max_length=500)),
                ('date_created', models.CharField(default='No date', max_length=500)),
                ('album_cover_art', models.CharField(default='no_img', max_length=5000, null=True)),
                ('parent_playlist', models.ForeignKey(db_column='parent_playlist_id', on_delete=django.db.models.deletion.CASCADE, to='spotify_app.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='RecProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hdbscan', picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True)),
                ('user_train_scaler', picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True)),
                ('user_df_features_obj', picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True)),
                ('user_df_scaled_obj', picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True)),
                ('user_top_clusters_obj', picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True)),
                ('user_has_objects', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
